/* Copyright (C) 2023 Beangle
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * jstart launch spec 的渲染与共用小工具。
 *
 * `basctl start`（按 farm）与 `basctl run`（单应用快速运行）生成的是同一种 spec：
 * `[app]` 声明入口（单应用）与组件目录，`[engine]` 声明 init 命令行与容器依赖，
 * 可选的 `[runtime]` / `[args]` 分别承载 JVM 参数与应用参数；多 webapp
 * （`tomcat-server`）时再用若干 `[subapp <id>]` 段。
 *
 * 本模块只负责拼文本与转义，不做 IO，也不调用 jstart。
 */
module bas.spec;

import std.array : appender;
import std.process : environment;
import std.string : replace, strip;

/** 一个 `[subapp <id>]` 段：webapp 的本地入口、上下文路径与扩展依赖。 */
struct SubappSpec {
  string id;
  string entry;
  string path;
  string libs;
}

/**
 * 渲染 launch spec。
 *
 * `entry` 非空时写单应用 `[app] entry`（嵌入式运行一个 webapp）；否则由 `subapps`
 * 逐段渲染多应用 `[subapp <id>]`。`baseRoot` 与 `instance` 一起决定 jstart 的组件
 * 目录 `<baseRoot>/<instance>`，`workingDir` 为空时不写 `[app] working_dir`。
 */
string renderLaunchSpec(string baseRoot, string instance, string workingDir, string initCommand,
    const(string)[] engineDeps, const(string)[] runtimeArgs, const(string)[] appArgs,
    const(SubappSpec)[] subapps, string entry = "") {
  auto sb = appender!string;
  sb.put("# Generated by basctl. Do not edit.\n\n");
  sb.put("[app]\n");
  if (entry.length)
    sb.put("entry = " ~ entry ~ "\n");
  sb.put("base = " ~ baseRoot ~ "\n");
  if (instance.length)
    sb.put("instance = " ~ instance ~ "\n");
  if (workingDir.length)
    sb.put("working_dir = " ~ workingDir ~ "\n");
  sb.put("\n[engine]\n");
  sb.put("init = " ~ initCommand ~ "\n");
  foreach (dep; engineDeps)
    sb.put(dep ~ "\n");
  if (runtimeArgs.length) {
    sb.put("\n[runtime]\n");
    foreach (arg; runtimeArgs)
      sb.put(arg ~ "\n");
  }
  if (appArgs.length) {
    sb.put("\n[args]\n");
    foreach (arg; appArgs)
      sb.put(arg ~ "\n");
  }
  foreach (app; subapps) {
    sb.put("\n[subapp " ~ app.id ~ "]\n");
    sb.put("entry = " ~ app.entry ~ "\n");
    sb.put("path = " ~ (app.path.length ? app.path : "/") ~ "\n");
    if (app.libs.length)
      sb.put("libs = " ~ app.libs ~ "\n");
  }
  return sb.data;
}

/**
 * jstart 的 `[engine] init` 命令行：调用本 basctl 的 `make <type>`。
 * jstart 自己完成分词，所以路径含空格时按 shell 规则加引号即可，无需 wrapper 脚本。
 */
string engineInitCommand(string containerType = "tomcat-server") {
  return shellQuote(basctlExecutable()) ~ " make " ~ containerType;
}

/** 覆盖 basctl 可执行文件位置的环境变量名（与 `beangle_jstart` / `beangle_setline` 同约定）。 */
enum basctlEnvVar = "beangle_basctl";

/**
 * basctl 可执行文件路径：优先环境变量 {@link basctlEnvVar}，否则用 `/proc/self/exe`，
 * 最后退回 `PATH` 上的 `basctl`。
 */
string basctlExecutable() @trusted {
  auto fromEnv = strip(environment.get(basctlEnvVar, ""));
  if (fromEnv.length)
    return fromEnv;
  version (linux) {
    import std.file : readLink;

    try {
      auto self = readLink("/proc/self/exe");
      if (self.length)
        return self;
    } catch (Exception) {
      // 忽略：退回 PATH 查找
    }
  }
  return "basctl";
}

/** 单引号包裹 shell 参数（内嵌单引号按 `'\''` 转义）。 */
string shellQuote(string s) {
  return "'" ~ s.replace("'", "'\\''") ~ "'";
}
